from enum import Enum


class ScraperErrorCode(Enum):
    MISSING_PARAM = "MISSING_PARAM"
    PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
    INVALID_DOMAIN = "INVALID_DOMAIN"
    CONNECTION_ERROR = "CONNECTION_ERROR"
    PRICE_PARSING_ERROR = "PRICE_PARSING_ERROR"
    SCRAPING_ERROR = "SCRAPING_ERROR"